// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTXSmH6zxBLqGxS-mXQHzq26wQdEQDoMs',
    appId: '1:490073427340:web:4157404c95d7b854e81aa9',
    messagingSenderId: '490073427340',
    projectId: 'takehomechallenge-2ce6f',
    authDomain: 'takehomechallenge-2ce6f.firebaseapp.com',
    storageBucket: 'takehomechallenge-2ce6f.appspot.com',
    measurementId: 'G-K2NKF0D11G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd5NjezhLitDqXRz3K9jJJpoMabT36Uw0',
    appId: '1:490073427340:android:1bb46ac051f7d760e81aa9',
    messagingSenderId: '490073427340',
    projectId: 'takehomechallenge-2ce6f',
    storageBucket: 'takehomechallenge-2ce6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS4KFMjrvAjMnXXTQID4dFGEd9wP1CdcA',
    appId: '1:490073427340:ios:2c131ae35be46d17e81aa9',
    messagingSenderId: '490073427340',
    projectId: 'takehomechallenge-2ce6f',
    storageBucket: 'takehomechallenge-2ce6f.appspot.com',
    iosBundleId: 'com.example.takeHomeChallenge',
  );
}
